import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Suspense } from 'react'

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'], // Укажите поддерживаемые символы (latin, cyrillic и т. д.)
  weight: ['400', '700'], // Укажите нужные веса
  display: 'swap', // Улучшает рендеринг шрифтов
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CalendarLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <Suspense>{children}</Suspense>
}
